[김은혜] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/27-westagram-backend-3-team- pull request #10
Opened 2021-11-19 10:39 UTC by ghimlilo

-브랜치 수정+이전 멘토 수정요청 사항 반영

2021-11-21 08:19 UTC, ghimlilo commented
-compile 삭제 
-if email, password 병합
-에러 메세지 수정

2021-11-21 09:41 UTC, ghimlilo commented
-IntegrityError의 문제는 등록된 user가 있을 경우, 에러 발생 후에 새로운 user를 등록할 때, pk가 앞선 회원가입 시도시(같은 이메일) 생성된 번호를 건너 뛰기 때문에, if exists를 사용하여 수정함

2021-11-21 15:22 UTC, kyeongraekim requested changes
은혜님 안녕하세요~ 아래 내용 확인해주시고 수정해주세요!

2021-11-21 15:22 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +from django.db        import IntegrityError
django 에서 import한 모듈이니 5번 라인으로 옮겨주셔야 더 깔끔할 것 같아 보이네요!~

2021-11-21 15:22 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +            if not re.match(email_validation, email) or not re.match(password_validation, password):
이메일과 패스워드 각각에 대한 에러임을 확인 할 수 있게 validation 에러에 대한 조건절을 나눠주심을 권장드립니다!~

2021-11-21 15:22 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +                return JsonResponse({"MESSAGE":"REGISTERED_ERROR"}, status = 400)
리턴해주시는 메세지명이 조금 명확하지 않아 보이네요! "User_Already_Exists" 정도의 중복가입을 명시하는 리턴메세지를 전달해보는 것은 어떨까요?

2021-11-21 15:22 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +
두칸의 공백이 불필요 해보입니다!~

2021-11-21 15:22 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +        except KeyError:
키에러외에도 다양한 에러를 핸들링 해보실 수 있을 것 같습니다!~ 발생할 수 있는 에러가 키에러외에 혹시 어떤 것들이 있을까요?

2021-11-21 15:22 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +                contact  = data["contact"],
contact 부분도 try 직후에 선언하셔서 키에러를 보다 앞선에서 잡을 수 있게 수정해보시는 것은 어떨가요?

2021-11-22 02:24 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +from django.db        import IntegrityError
수정완료 하였습니다!

2021-11-22 02:28 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +            if not re.match(email_validation, email) or not re.match(password_validation, password):
이전 버전에서 해당 부분을 분리하여 에러를 각각 리턴하였는데, 이유는 사용자가 어떠한 이유로 회원가입이 거절 되었는지 즉, 이메일의 오류 인지, 패스워드 오류인지 구분하고자 분리하여 에러를 리턴하였는데, 다른 리뷰 의견으로 다시 병합하였습니다. 라운지 시간에 해당 건에 대하여 질문드리고 싶습니다!

2021-11-22 02:28 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +                return JsonResponse({"MESSAGE":"REGISTERED_ERROR"}, status = 400)
변경하였습니다!

2021-11-22 02:28 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +
변경하였습니다!

2021-11-22 02:32 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +        except KeyError:
IntegrityError를 지정해보고 싶어서(if문을 줄이고) 해당 에러를 import 하고, 하단에서 에러를 지정해주었는데, 이 에러는 정확하게 어떤 부분의 오류의 문제인지 알 수 없다는 리뷰를 받아서, 삭제하고 조건절을 추가하여 validation error로 수정하여 올렸습니다. 그렇다면 이외에 또 다른 에러를 핸들링 하는 것에 대하여 의견을 주신건지요?

2021-11-22 02:32 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +                contact  = data["contact"],
수정하였습니다!

2021-11-22 02:51 UTC, kyeongraekim requested changes
은혜님~ 일단 수정 가능한 부분 반영해주시고 이따 라운지 세션 때 더 질문 받으러 가겠습니다!~

2021-11-22 02:51 UTC, kyeongraekim commented on students/eunhyekim/users/urls.py
> +    path('', SignUpView.as_view()),
url이 빈스트링 값보다 /signup 정도로 선언해주셔서 최종 url 엔드포인트가 users/signup 으로 설정된다면 추후에 유저스에 맞물리는 엔드포인트들과 구분을 지어줄 수 있겠네요!

2021-11-22 02:51 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +
줄바꿈 공백은 한칸이면 충분해보입니다!~

2021-11-22 02:51 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +            if not re.match(email_validation, email) or not re.match(password_validation, password):
네 은혜님 라운지 때 질문 받으러 내려가겠습니다!~

2021-11-22 02:51 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +            User.objects.create(
이곳은 줄바꿈 공백이 한 칸 있으면 좋을 것 같네요!~

2021-11-22 02:51 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +        except KeyError:
이 부분도 점심식사 드시고 오후에 뵈서 말씀 나눌게요~

2021-11-22 06:14 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +            User.objects.create(
수정하였습니다!

2021-11-22 06:16 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +            if not re.match(email_validation, email) or not re.match(password_validation, password):
수정하였습니다!

2021-11-22 06:16 UTC, ghimlilo commented on students/eunhyekim/users/urls.py
> +    path('', SignUpView.as_view()),
수정하였습니다!

2021-11-22 06:17 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +
수정하였습니다!

2021-11-22 07:13 UTC, kyeongraekim approved these changes

2021-11-22 07:13 UTC, kyeongraekim commented
LGTM!~

2021-11-22 07:13 UTC, merged