[김은찬] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/27-westagram-backend-3-team- pull request #11
Opened 2021-11-21 06:26 UTC by Daco2020

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일, 패스워드 정규표현식 추가 -> 이메일과 패스워드 각기 다른 에러메시지 노출하도록 구분하였으며 추후 로그인시에도 사용하기 위해 정규식 패턴을 클래스 바깥 변수에 할당하였음
- 이메일 중복 에러의 경우 full_clean을 활용하여 ValidationError으로 반환하도록 함. 또한 자세한 에러메시지를 보여주기 위해 에러내용을 함께 노출함
- 키 에러의 경우에도 유저가 쉽게 에러를 인지하고 수정할수 있도록 에러메시지를 함께 노출함 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 중복을 잡아낼때 처음엔 IntegrityError 를 이용해보았는데, 해당 에러를 사용하면 에러는 잡아내지만, 다음 데이터를 저장할때 테이블의 pk번호가 증가하는 것을 확인하였습니다. pk번호가 비정상적으로 증가되는 것은 추후 문제가 생길 수 있다고 판단하여 로직을 수정하였는데, 이런 현상의 정확한 원인을 몰라 질문 드립니다. 제 예상으로는 먼저 데이터가 테이블에 저장되고 그 뒤 이메일 중복이 확인되자 다시 데이터를 지우는 과정이 있는 것 같습니다. (스크린샷 첨부드립니다)![스크린샷 2021-11-21 오후 3.03.14.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/cc4dedcb-7cb5-4c41-94c3-790dea78a4a6/스크린샷_2021-11-21_오후_3.03.14.png)
![image](https://user-images.githubusercontent.com/76890895/142752140-ab1136cb-5fe1-4337-81c0-4adf55db138f.png)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-21 15:14 UTC, kyeongraekim requested changes
아래 내용 참고해서 수정해주세요!~

2021-11-21 15:14 UTC, kyeongraekim commented on students/eunchan/westagram/users/views.py
> +        except KeyError as e:
해당 내용과 같이 전체 에러메세지를 반환하는 행동은 지양해주셔야 합니다. 개발단계에서의 디버깅 시 보다 정확한 에러메세지를 확인하기 위해 사용될 수 는 있겠으나, 클라이언트/프론트 단에서 리턴 메세지를 받았을 시 불필요한 내부 코드까지 그 내용을 전달 할 수 있고 이는 보안성의 취약점으로 직결되기 때문입니다.

2021-11-21 15:14 UTC, kyeongraekim commented on students/eunchan/westagram/users/views.py
> +                    information  = data["information"]
위 내용도 try문 시작 직후 이메일, 패스워드에 대한 키매핑을 해주신 것 처럼 위에 적어주시는 것을 추천드립니다. 불필요하게 추가 코드를 훑을 필요 없이 앞단에서 키에러 문제를 잡을 수 있어 보이네요!

그리고 모델 기획상 information 은 blank=True 가 기본 값이네요! 파이썬의 또 다른 메소드인 .get() 을 써서 blank 값이 적힐 수 있는 기획에 맞게 코드를 정리해보세요!~

2021-11-21 15:14 UTC, kyeongraekim commented on students/eunchan/westagram/users/views.py
> +            else :
elif, else 문이 꼭 필요한지 논리적 구조를 다시 한 번 생각해보세요!~

2021-11-22 01:10 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
> +                    information  = data["information"]
![image](https://user-images.githubusercontent.com/76890895/142787041-691aa248-6369-46cc-9acd-c178fcc94be9.png)
- 앞서 키매핑을 함으로써 키에러를 효율적으로 잡을 수 있도록 수정하였습니다!
- get()을 이용해 입력값이 없는 경우 공백이 들어가도록 수정하였습니다!
피드백 덕분에 키에러의 원리에 대해 이해할 수 있었습니다. 감사합니다.

2021-11-22 01:11 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
> +            else :
![image](https://user-images.githubusercontent.com/76890895/142787198-5873e8d9-920e-4c15-942c-d8e3f2a153e9.png)
elif를 if 로 else는 사용하지 않도록 수정하였습니다.!

2021-11-22 01:12 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
> +        except KeyError as e:
![image](https://user-images.githubusercontent.com/76890895/142787245-bb24bab5-203d-43c6-8791-66845468a488.png)
- 전체 에러코드가 반환되지 않도록 메시지를 수정하였습니다!

2021-11-22 02:08 UTC, kyeongraekim requested changes
작은 수정사항이 남아 있습니다 은찬님~ 마저 반영해주세요!

질문 및 특이사항으로 남겨주신 내용에 대한 답변들 드리자면 말씀해주신 내용처럼 데이터가 쌓였다가 뒤늦게 빠지는 구조로 pk값이 추가되는 현상으로 보여집니다. 해당 내용을 미연에 방지하기 위해서는 transaction 기능을 사용해서 애초에 회원가입 데이터가 들어가지 않게 설정하는 방법을 해결책으로 제시해드릴 수 있겠습니다!

추가사항으로 IntegrityError 보다 외래키 변경 등 db 무결성이 영향 받는 보다 다양한 원인으로 인해 발생될 수 있습니다. 회원가입시 중복 이메일은 개발자 기획 차원에서 보다 국소적인 방법으로 핸들링 해주시는 것을 추천드립니다!~

2021-11-22 02:08 UTC, kyeongraekim commented on students/eunchan/westagram/users/views.py
> +            return JsonResponse({'massage':"VALIDATION_ERROR"}, status=400)
if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_EMAIL_ADDRESS')
        
   - import 해주신 ValidationError를 다소 수동적으로 일으키는 방법이 아닌, 를 보다 active 하게 사용하는 기획으로, 위와 같이 if 문 내에서 except 문에 걸릴 때 직접 raise 할 수 있게 변경해보세요!~ 
   
   - 그리고 해당 리뷰 내용은 추후 validations.py 로의 모듈화를 위한 사전 연습(?)의 일환임을 미리 말씀드립니다 ㅎㅎ! validation을 잡아주는 파일을 따로 만들어서 import 해주고, view에서는 validation Error를 except 로 잡는 내용에 대한 원리를 하나씩 깨우쳐가기위해 단계별로 리뷰를 달아드렸습니다!~ 미리 참고만해주시고 4단계에 한번 모듈화에 도전해보세요!~

2021-11-22 02:08 UTC, kyeongraekim commented on students/eunchan/westagram/westagram/settings.py
>  # m1 맥북
불필요한 한글 주석 삭제해주세요!~

2021-11-22 02:47 UTC, Daco2020 commented on students/eunchan/westagram/westagram/settings.py
>  # m1 맥북
앗 넵 삭제하였고 추가적으로 불필요한 공백 줄도 함께 삭제하였습니다.

2021-11-22 05:17 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
> +            return JsonResponse({'massage':"VALIDATION_ERROR"}, status=400)
![image](https://user-images.githubusercontent.com/76890895/142804626-55fee4e5-bbae-4514-bde0-82cf5700336b.png)
- if에서 validationError로 빠지게 하였습니다!
- 이메일 중복을 가장 첫 단계에서 if로 잡아내도록 하였는데, 이떄문에 if가 늘어났습니다. 현재 코드처럼 국소적으로 각각 에러를 핸들리하는 것이 좋을지, if 문 하나에 위 세개의 if를 and나 or로 합치는게 나은 로직인지 궁금합니다!
- 추가적으로 raise로 에러메시지를 지정해두면 해당 메시지는 나중에 어디서 확인할 수 있나요? 현재 터미널에서는 최종적으로 VALIDATION_ERROR 만 노출됩니다!

2021-11-22 06:25 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
> +            return JsonResponse({'massage':"VALIDATION_ERROR"}, status=400)
해당 질문 답변받아 수정했습니다 감사합니다 경래님!

2021-11-22 07:57 UTC, bigfanoftim requested changes

2021-11-22 07:57 UTC, bigfanoftim commented on students/eunchan/westagram/users/views.py
> +password_regexp = "^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&(){}\[\]])[A-Za-z\d@$!%*#?&(){}\[\]]{8,}$"
정규표현식을 굳이 `SignupView`밖에 작성해주신 이유가 있을까요?

2021-11-22 07:57 UTC, bigfanoftim commented on students/eunchan/westagram/users/views.py
> +            information  = data.get("information","")
```python
information  = data.get("information","")
```
이 부분에서 `information` key를 통해 value를 받아오거나 아니면 공백을 넣어주시려는 것 같은데,  그러면 `models.py`에서 `default` 속성이 필요없지 않을까요?

2021-11-22 08:05 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
> +password_regexp = "^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&(){}\[\]])[A-Za-z\d@$!%*#?&(){}\[\]]{8,}$"
![image](https://user-images.githubusercontent.com/76890895/142824945-ac9994c6-6cbf-451b-9933-6f1754aef1a9.png)
로그인뷰에서도 정규표현식을 사용하기 위해 작성해두었습니다. 로그인시에 사용자가 오타로 정규표현식 범위를 벗어난 입력값을 주었을 경우 굳이 DB까지 가지 않고 뷰 단계에서 걸러주려고 합니다.!

2021-11-22 08:24 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
> +            information  = data.get("information","")
해당 공백을 삭제하였습니다!

2021-11-22 08:47 UTC, merged