[염기욱] Mission 2: 모델링
wecode-bootcamp-korea/27-westagram-backend-3-team- pull request #12
Opened 2021-11-22 03:40 UTC by bakha1002

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장고 앱 모델링
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- users 앱 생성 및 models.py 작성
- migration 진행

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-22 08:00 UTC, bigfanoftim requested changes

2021-11-22 08:00 UTC, bigfanoftim commented on students/giuk/westagram/users/models.py
> +# Create your models here.
불필요한 주석 삭제해주세요!!
```suggestion
```

2021-11-22 08:00 UTC, bigfanoftim commented on students/giuk/westagram/users/models.py
> +    email        = models.EmailField()
`email field`에 `unique` 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!
공식 문서에서 그 방법을 찾아보고 적용해주세요.
그리고 `max_length` 속성도 추가해주시면 좋을 것 같습니다!

2021-11-22 08:00 UTC, bigfanoftim commented on students/giuk/westagram/users/models.py
> +    password     = models.CharField(max_length=45)
`password`는 이후에 암호화해서 저장해야하기 때문에 `max_length=200`으로 수정해주세요.

2021-11-23 01:46 UTC, bakha1002 commented on students/giuk/westagram/users/models.py
> +# Create your models here.
삭제했습니다!

2021-11-23 01:52 UTC, bakha1002 commented on students/giuk/westagram/users/models.py
> +    email        = models.EmailField()
수정했습니다!

2021-11-23 01:53 UTC, bakha1002 commented on students/giuk/westagram/users/models.py
> +    password     = models.CharField(max_length=45)
수정했습니당

2021-11-23 02:04 UTC, merged