[김은혜] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/27-westagram-backend-3-team- pull request #13
Opened 2021-11-22 07:35 UTC by ghimlilo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-22 10:34 UTC, jincastle commented on students/eunhyekim/users/views.py
> +                return JsonResponse({'message':'INVALID_USER'}, status = 400)
!= 대신 not을 쓴 이유가 있을까요?? # #

2021-11-22 10:38 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +                return JsonResponse({'message':'INVALID_USER'}, status = 400)
미처 생각하지 못했네요! 수정해보겠습니다! 감사합니다!

2021-11-22 11:56 UTC, Daco2020 commented on students/eunhyekim/users/urls.py
> +from users.views        import SignUpView, SignInView
import 사이에 한 줄 띄어야 할 것 같아요~!

2021-11-22 13:32 UTC, ghimlilo commented on students/eunhyekim/users/urls.py
> +from users.views        import SignUpView, SignInView
오! 감사합니다!

2021-11-22 15:53 UTC, kyeongraekim requested changes
은혜님 밤늦게까지 고생이 많습니다 ㅎㅎ 내일 아침에 일어나시면 아래의 내용 확인하셔서 수정해주세요!~

2021-11-22 15:53 UTC, kyeongraekim commented on students/eunhyekim/Westagram/settings.py
> +APPEND_SLASH = True
APPEND_SLASH 는 False 로 설정해주세요~

2021-11-22 15:53 UTC, kyeongraekim commented on students/eunhyekim/users/validation.py
> +
불필요한 줄바꿈 공백은 삭제해주세요~

2021-11-22 15:53 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +                return JsonResponse({'message':'INVALID_USER'}, status = 400)
!= 를 사용했을 때와  not을 사용했을 때 두 내용의 차이점은 무엇일까요?

2021-11-22 15:53 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +            password = User.objects.get(email = data["email"]).password
password를 기준으로 변수를 선언하는 것보다 user를 기준으로 잡는게 아래 except 문과 더 연결성이 드러나면서 보다 명확한  로직과 가독성을 띌 것 같습니다~

2021-11-22 15:53 UTC, kyeongraekim commented on students/eunhyekim/users/validation.py
> +        raise ValidationError("PassWord_Invalidation")
이메일에 맞는, 패스워드에 맞는 두 함수로 validation을 분리해주세요~ 각각의 한가지 함수는 하나의 기능을 하는 것이 모듈화의 핵심입니다~ 먼 미래의 확장성을 고려한 코드를 지향해주세요!

2021-11-22 16:09 UTC, ghimlilo commented on students/eunhyekim/users/validation.py
> +        raise ValidationError("PassWord_Invalidation")
네! 수정하였습니다!

2021-11-22 16:11 UTC, ghimlilo commented on students/eunhyekim/Westagram/settings.py
> +APPEND_SLASH = True
수정하였습니다!

2021-11-22 16:11 UTC, ghimlilo commented on students/eunhyekim/users/validation.py
> +
삭제하였습니다!

2021-11-22 16:31 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +            password = User.objects.get(email = data["email"]).password
만약 email 기준으로 변수를 잡는 경우, 등록된 user에서 비밀번호가 같은 user가 있는 경우(인증 단계를 거치지 않은,,, hash, salting 하기 전의 단순 비밀번호) 여러 개의 이메일 값이 반환되어 로그인에 실패하여 password 기준으로 변수를 잡은 것인데, 조건문을 추가하여서라도??? email 기준으로 변수를 선언하는 것이 더 명확한 로직이 되는 것인지 궁금합니다!

2021-11-23 01:55 UTC, kyeongraekim requested changes
다음 내용 추가 수정 반영해주세요!~

2021-11-23 01:55 UTC, kyeongraekim commented on students/eunhyekim/users/validation.py
> +def Validation_Email(email):
함수명은 모두 파이썬 컨벤션에 맞게 소문자로 네이밍 해주세요!~

2021-11-23 01:55 UTC, kyeongraekim commented on students/eunhyekim/users/validation.py
> +        raise ValidationError("User_Already_Exists")
해당 내용은 validation의 의미와 기능상 view 에서 코드로직으로 풀어서 쓰는 것을 더 권장드립니다!~

2021-11-23 01:55 UTC, kyeongraekim commented on students/eunhyekim/users/views.py
> +            password = User.objects.get(email = data["email"]).password
조건문을 추가하는 의도가 아니었습니다 ㅎㅎ  아래와 같이 작성하는 것이 더 가독성이 좋아 보이겠네요!~

            user = User.objects.get(email=data['email'])

            if user.password != data['password']:
                return JsonResponse({'message': 'INVAILD_USERS'}, status=401)

2021-11-23 01:57 UTC, bigfanoftim requested changes

2021-11-23 01:57 UTC, bigfanoftim commented on students/eunhyekim/users/views.py
> +                return JsonResponse({'message':'INVALID_USER'}, status = 400)
로그인 시 불필요하게 변수를 지정할 필요가 없어 보입니다. 그저 request를 통해 받아온 email과 password를 동시에 만족하는 경우만 핸들링 해주면 될 것 같습니다! 
```suggestion
            if not User.objects.filter(email = data["email"], password = data["password"]).exists():
	        return JsonResponse({'message' : 'INVALID_USER'}, status=401)
```

2021-11-23 02:24 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +            password = User.objects.get(email = data["email"]).password
수정하였습니다!

2021-11-23 02:24 UTC, ghimlilo commented on students/eunhyekim/users/validation.py
> +def Validation_Email(email):
수정하였습니다!

2021-11-23 02:25 UTC, ghimlilo commented on students/eunhyekim/users/validation.py
> +        raise ValidationError("User_Already_Exists")
네! 안그래도 의문점이였었는데,,, 수정하였습니다! 감사합니다!

2021-11-23 02:26 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +                return JsonResponse({'message':'INVALID_USER'}, status = 400)
네 이해하였습니다! 수정했습니다!

2021-11-23 02:40 UTC, ghimlilo commented on students/eunhyekim/users/views.py
> +                return JsonResponse({'message':'INVALID_USER'}, status = 400)
비교연산자, 논리연산자, 값, 객체, 포인터, 메모리,,,,,, Q&A시간에 질문해도 될까요???!!!

2021-11-23 07:09 UTC, merged