[박진성] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/27-westagram-backend-3-team- pull request #14
Opened 2021-11-22 07:44 UTC by jincastle

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
로그인 기능구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [o] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [o] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [o] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-22 10:35 UTC, ghimlilo commented on students/jinsungpark/users/views.py
> +                return JsonResponse({"result" : "KEY_ERROR"}, status=400)
키에러는 값의 오류가 아닌 키의 오류일 때 에러를 발생시키는 것으로 알고 있습니다. 키에러는 가장 하단으로(바깥으로) 내려서 키값의 오류만을 체크 하고, 만약 전달된 값이 공백일 때의 에러를 발생 시키는 것은 DoesNotExist로 같이 오류로 리턴하면 가장 상단 if 조건을 생략 할 수 있지 않을까 합니다!

2021-11-22 11:33 UTC, jincastle commented on students/jinsungpark/users/views.py
> +                return JsonResponse({"result" : "KEY_ERROR"}, status=400)
맞네요 DoesNotExis로 하면 위에 코드 2개다 지울수 있네요 감사합니다

2021-11-22 11:50 UTC, Daco2020 commented on students/jinsungpark/users/views.py
> +
status = 500 오타난 것 같습니다.

2021-11-22 11:56 UTC, jincastle commented on students/jinsungpark/users/views.py
> +
수정완료했습니다.  감사합니다.

2021-11-22 15:39 UTC, kyeongraekim requested changes
로그인 뷰 아래 내용 수정해주시고 validation.py 모듈화에도 한 번 도전해보세요!~

2021-11-22 15:39 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +
마지막 부분에 불필요한 공백이 몇 줄 보이네요!~
그리고 try-except 로 걸 때 필히 나올 확률이 높은 Key_Error는 핸들링 해주고 계시지 않네요!~

2021-11-22 15:39 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +            if user_info.passwd != password:
user_info.passwd 보다 가독성을 높이기위해 user.password 로 받을 수 있게 수정해주시는 것을 권장드립니다!~

2021-11-23 01:29 UTC, jincastle commented on students/jinsungpark/users/views.py
> +            if user_info.passwd != password:
user = User.objects.get(email=email)
    if user.passwd != password: 
    로 변경했습니다.

2021-11-23 01:29 UTC, jincastle commented on students/jinsungpark/users/views.py
> +
except KeyError:
              return JsonResponse({"message" : "KEY_ERROR"}, status=400)
추가하여 핸들링 하였습니다.

2021-11-23 07:31 UTC, kyeongraekim requested changes
아래 내용 참고해서 수정해주세요!~

2021-11-23 07:31 UTC, kyeongraekim commented on students/jinsungpark/users/validation.py
> +def Signup_email(email):
함수명 네이밍시 모두 소문자로 통일해주세요.
그리고 보다 정확한 기능적 의미를 나타내야함으로 validate_email 정도로 바꾸어 주세요!~ 아래 비밀번호 부분도 동일하게 적용되어야 하는  부분입니다!

2021-11-23 07:31 UTC, kyeongraekim commented on students/jinsungpark/users/validation.py
> +    passwd_regex = '^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$'
정규표현식을 변수처리 하실 때 변수명은 모두 대문자로 바꾸어 주세요!~

2021-11-23 07:31 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +                raise ValidationError("EMAIL_ALREADY_EXISTS")
view 로직선에서 해결할 수 있는 부분은 에러 Raise 외에 JsonResponse 로 바꾸어 주시면 불필요하게 아래를 더 훑을 필요 없이 해당 코드선에서 로직 흐름이 멈출 것 같아 보이네요~

2021-11-23 07:31 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +            if User.objects.passwd != password:
passwd 로 모델에 아예 약어로 반영이 되어있네요! 해당 부분 모델 수정과 함께 다시 수정해주세요~

2021-11-23 08:20 UTC, merged