[김은찬] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/27-westagram-backend-3-team- pull request #15
Opened 2021-11-22 12:36 UTC by Daco2020

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- validations 모듈을 추가하여 에러를 별개 파일에서 핸들링

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-22 15:27 UTC, ghimlilo commented on students/eunchan/westagram/users/views.py
>              information  = data.get("information")
information data를 가져올 때, 즉 모델에서 blank = True가 기본값인  경우, get 메소드를 사용해야 하는 이유가 궁금합니다!

2021-11-23 01:08 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
>              information  = data.get("information")
![image](https://user-images.githubusercontent.com/76890895/142957074-4f9d1b4b-cd5b-4a15-b9e9-5e914018c6bd.png)
get을 이용할때 만약 값이 없다면 null이 테이블에 들어가게 됩니다! 현재 모델 null=True로 넣어주었습니다!
get에 공백을 기본값으로 지정해줄수도 있지만 공백이나 null이나 유의미한 차이가 없기때문에 따로 공백을 지정하지 않고 null이 들어가도록 하였습니다!

2021-11-23 01:38 UTC, jincastle commented on students/eunchan/westagram/users/validations.py
> +
전역변수 활용한 이유가 있을까요?

2021-11-23 01:39 UTC, Daco2020 commented on students/eunchan/westagram/users/validations.py
> +
지당하신 말씀입니다~! 모듈화로 옮기면서 전역변수에 넣을 필요가 없어졌네요~~ 호다닥 수정하였습니다. 감사합니다.

2021-11-23 02:03 UTC, bigfanoftim requested changes

2021-11-23 02:03 UTC, bigfanoftim commented on students/eunchan/westagram/users/urls.py
> +    path('/login', LoginView.as_view())
들여쓰기 맞춰주세요~

2021-11-23 02:03 UTC, bigfanoftim commented on students/eunchan/westagram/users/validations.py
> +        raise Member.DoesNotExist
`validations.py`는 반복되는 정규표현식을 처리하기 위해 따로 모듈로 만들었을 뿐인데 email 중복 여부와 password 체크는 해당 모듈의 생성 이유와 맞지 않습니다. 실제로 회원가입시 이 모듈을 불러와서 사용할텐데 불필요한 password 체크 함수가 따라오는 상황입니다. 저런 로직들은 실제 view 안에서 처리해주세요
```suggestion
```

2021-11-23 02:03 UTC, bigfanoftim commented on students/eunchan/westagram/users/views.py
> +            password_match_check(email, password)
위에서 말씀드린대로 해당 view에서 로직으로 다시 작성해주세요

2021-11-23 04:15 UTC, Daco2020 commented on students/eunchan/westagram/users/urls.py
> +    path('/login', LoginView.as_view())
![image](https://user-images.githubusercontent.com/76890895/142970429-fc1a729b-9421-4c74-a596-c372e8575487.png)
수정하였습니다.

2021-11-23 04:16 UTC, Daco2020 commented on students/eunchan/westagram/users/validations.py
> +        raise Member.DoesNotExist
해당 로직은 뷰 파일에서 수행하도록 수정하였습니다!

2021-11-23 06:44 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
> +            password_match_check(email, password)
수정 완료하였습니다~!

2021-11-23 07:21 UTC, merged