[김은찬] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/27-westagram-backend-3-team- pull request #17
Opened 2021-11-23 08:01 UTC by Daco2020

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 비밀번호 암호화 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입시 입력한 비밀번호를 암호화 하여 디비에 저장하도록 로직을 수정하였음

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-23 08:29 UTC, jincastle commented on students/eunchan/westagram/users/views.py
> +            decoded_password = encoded_password.decode('utf-8')
한줄로 줄이면 메모리 한번만 사용해도 될거 같아요

2021-11-23 08:50 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
> +            decoded_password = encoded_password.decode('utf-8')
넵 감사합니다 수정 반영하였습니다!

2021-11-23 16:02 UTC, kyeongraekim requested changes
아래 내용 확인해주시고 수정해주세요!~

2021-11-23 16:02 UTC, kyeongraekim commented on students/eunchan/westagram/users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'),bcrypt.gensalt()).decode('utf-8')
논리상 아래 정규표현식을 다 통과한 이후에 hashed_password가 선언되야함이 맞겟죠? 고민해보시고 수정에 반영해보세요!~

2021-11-24 01:21 UTC, Daco2020 commented on students/eunchan/westagram/users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'),bcrypt.gensalt()).decode('utf-8')
코드를 봐보니 데이터가 DB로 들어가기 직전에 암호화하는 것이 가장 효율적인 것 같아 create 직전으로 위치를 변경하였습니다!

2021-11-24 01:37 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-11-24 01:38 UTC, merged