[박진성] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/27-westagram-backend-3-team- pull request #18
Opened 2021-11-23 08:27 UTC by jincastle

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 암호화
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-23 08:50 UTC, ghimlilo commented on students/jinsungpark/users/views.py
> +
저의 경우에는, 변수를 두번 나눠서 선언하였는데, 한 번에 변수를 정리하셔서 가독성이 더 좋아보이네요! LGTM~!

2021-11-23 08:53 UTC, Daco2020 commented on students/jinsungpark/users/views.py
> +                passwd   = hashed_password,
passwd -> password 수정하는게 추후 혼란이 적을 것 같습니다!

2021-11-23 08:55 UTC, jincastle commented on students/jinsungpark/users/views.py
> +
감사합니다.

2021-11-23 08:56 UTC, jincastle commented on students/jinsungpark/users/views.py
> +                passwd   = hashed_password,
개인적으로 진행하는거라 모델에서는 passwd로 진행하였습니다 나중에 팀프로젝트 진행시 좀더 가독성 좋게 진행하도록 하겠습니다. 감사합니다~~~~~~~~~~

2021-11-23 16:00 UTC, kyeongraekim requested changes
안녕하세요 진성님 다음 내용 확인하여 수정해주세요!~

2021-11-23 16:00 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
>          except KeyError:
validation 모듈에서 에러를 일으켰으니 이곳 except 문에서 해당 ValidationError를 잡아서 e.message로 원하는 커스터마이징된 메세지를 딱 잡아서 JsonResponse로 반환해주세요!~

2021-11-23 16:00 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +                passwd   = hashed_password,
해당 내용 모델 컬럼 명 바꾸는게 어렵지 않으니 저도 password로 바꾸는 걸 추천드립니다! 개발자는 아무리 사소한 내용이라도 수정/개선하는 작업을 귀찮아 해서는 안되는 직업임을 당부드립니다!~

2021-11-24 00:37 UTC, jincastle commented on students/jinsungpark/users/views.py
> +                passwd   = hashed_password,
넵 알겠습니다 .   수정완료했습니다.

2021-11-24 00:47 UTC, jincastle commented on students/jinsungpark/users/views.py
>          except KeyError:
로그인쪽에 validation 모듈을 사용하지 않았습니다. 그래서 ValidationError를 잡아서 e.message로 잡지 않았습니다

2021-11-24 01:16 UTC, kyeongraekim approved these changes
LGTM!~

2021-11-24 01:16 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
>          except KeyError:
네 확인했습니다!~ 그러면 해당 내용으로 진행하는 것으로 인지하고 있겠습니다!

2021-11-24 01:16 UTC, merged