[김은찬] Mission 2: 모델링
wecode-bootcamp-korea/27-westagram-backend-3-team- pull request #6
Opened 2021-11-18 08:54 UTC by Daco2020

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 유저 앱 생성
- member 테이블 생성을 위한 models 코드 작성

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- pr 이후 migrate 진행하겠습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-18 09:09 UTC, lordmyshepherd requested changes

2021-11-18 09:09 UTC, lordmyshepherd commented on students/eunchan/westagram/users/models.py
> +
주석 지워주시고 import문과 class 사이 간격이 한 칸이 되도록 수정해주세요~
```suggestion

```

2021-11-18 09:09 UTC, lordmyshepherd commented on students/eunchan/westagram/users/models.py
> +    person_info = models.CharField(max_length=200)
변수명을 줄여쓰지 않도록 주의해주세요!
```suggestion
    information = models.CharField(max_length=200)
```

2021-11-18 09:09 UTC, lordmyshepherd commented on students/eunchan/westagram/users/models.py
> +    phone_num = models.CharField(max_length=20)
```suggestion
    phone_number = models.CharField(max_length=20)
```

2021-11-18 09:10 UTC, kyeongraekim requested changes
은찬님~ 아래 내용 확인해서 수정해주세요!~

2021-11-18 09:10 UTC, kyeongraekim commented on students/eunchan/westagram/users/models.py
> +
불필요한 공백이 많아 보이네요!~  import문 이후에 한칸 내지 두칸만 띄어주셔도 됩니다 ㅎㅎ

2021-11-18 09:10 UTC, kyeongraekim commented on students/eunchan/westagram/users/models.py
> +class Member(models.Model):
위코드 컨벤션에 맞게 전체적으로 정렬 등을 신경써서 수정해주세요!~

컨벤션 전체 내용은 아래 링크를 참고해주세요!~

https://www.notion.so/wecode/wecode-Python-Coding-Convention-0a293f18b2244dfeb1005273d0a9dc75

2021-11-19 01:30 UTC, bigfanoftim requested changes

2021-11-19 01:30 UTC, bigfanoftim commented on students/eunchan/westagram/users/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
코드내에 클래스 단위로, 혹은 함수 단위로 = 을 기준으로 하여 코드 정렬해주세요!
```python
# BAD
point = models.DecimalField(max_digits=2, decimal_places=1)
user = models.ForeignKey('users.User', on_delete=models.CASCADE)
movie = models.ForeignKey('movie.Movie', on_delete=models.CASCADE)
created_at = models.DateField(auto_now_add=True)
updated_at = models.DateField(auto_now=True)

# GOOD
point      = models.DecimalField(max_digits=2, decimal_places=1)
user       = models.ForeignKey('users.User', on_delete=models.CASCADE)
movie      = models.ForeignKey('movie.Movie', on_delete=models.CASCADE)
created_at = models.DateField(auto_now_add=True)
updated_at = models.DateField(auto_now=True)
```

2021-11-19 07:24 UTC, merged