[김은혜] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/27-westagram-backend-3-team- pull request #8
Opened 2021-11-19 06:43 UTC by jincastle

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
회원가입 구현
		 
## 수정 사항들 자세한 내용
users/views.py 기능 구현

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [o ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [o] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [o] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-19 07:20 UTC, ghimlilo reviewed
정규표현식을  사용할 때, 패스워드에서 '^', '$'를 사용해서 앞뒤를 지정을 했을 때, 사용자가 순서대로 작성하지 않아도 오류검사에서 넘어가는지 궁금합니다!(이메일 오류 검사에서는 지정해줘야 하는 것은 알고 있는데, 패스워드에서는 왜 지정이 되어 있는건지가 궁금합니다)

2021-11-19 07:33 UTC, bigfanoftim requested changes

2021-11-19 07:33 UTC, bigfanoftim commented on students/jinsungpark/users/views.py
> +            passwd_condition = '^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$'
코드내에 클래스 단위로, 혹은 함수 단위로 = 을 기준으로 하여 코드 정렬해주세요!
```python
# BAD
point = models.DecimalField(max_digits=2, decimal_places=1)
user = models.ForeignKey('users.User', on_delete=models.CASCADE)
movie = models.ForeignKey('movie.Movie', on_delete=models.CASCADE)
created_at = models.DateField(auto_now_add=True)
updated_at = models.DateField(auto_now=True)

# GOOD
point      = models.DecimalField(max_digits=2, decimal_places=1)
user       = models.ForeignKey('users.User', on_delete=models.CASCADE)
movie      = models.ForeignKey('movie.Movie', on_delete=models.CASCADE)
created_at = models.DateField(auto_now_add=True)
updated_at = models.DateField(auto_now=True)
```

2021-11-19 07:33 UTC, bigfanoftim commented on students/jinsungpark/users/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=400)
`KeyError` 처리를 하는데 `except Exception:`으로 작성하신 이유가 있을까요?

2021-11-19 07:33 UTC, bigfanoftim commented on students/jinsungpark/users/views.py
> +            phone=data["phone"],
위와 동일합니다. 컨벤션 항상 신경써주세요

2021-11-19 07:47 UTC, jincastle commented on students/jinsungpark/users/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=400)
수정하는 과정에서 누락한거 같습니다. Exception. 삭제처리 하였습니다.

2021-11-19 07:48 UTC, jincastle commented on students/jinsungpark/users/views.py
> +            phone=data["phone"],
정리 완료하였습니다.

2021-11-19 07:48 UTC, jincastle commented on students/jinsungpark/users/views.py
> +            passwd_condition = '^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$'
정리 완료하였습니다.

2021-11-19 09:56 UTC, kyeongraekim requested changes
아래 내용 확인해서 수정해주세요!~

2021-11-19 09:56 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +from .models import User
불필요한 한글 주석 삭제해주세요!~

2021-11-19 09:56 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +            #     return JsonResponse({"message": "EMAIL_ERROR"}, status=400)
주석처리가 되어있네요? 혹시 의도하신 내용일까요?

2021-11-19 09:56 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +class UsersView(View):
파이썬 웹개발 컨벤션 상 클래스 명은 단수로 해주세요~ 그리고 회원가입 뷰이기 때문에 SignUpView or LogInView 가 더 어울리는 클래스 명이 되겠네요!~

2021-11-19 09:56 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +        except:
except 문이 위에서 발생할 수 있는 모든 에러를 Key_Error 로 막고 있네요!
except keyerror 로 키에러만 잡을 수 있게 해주세요!~

2021-11-19 09:56 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +            passwd = data["passwd"],
변수명 네이밍은 약어보다 전체 원어로 풀어쓰는 것을 권장드립니다!~

2021-11-19 09:56 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +            #     return JsonResponse({"message": "EMAIL_ERROR"}, status=400)
그리고 논리구조상 elif 가 꼭 필요한 내용인지 다시 한 번 생각해보세요!~

2021-11-19 11:15 UTC, jincastle commented on students/jinsungpark/users/views.py
> +from .models import User
삭제 완료하였습니다

2021-11-19 11:17 UTC, jincastle commented on students/jinsungpark/users/views.py
> +            #     return JsonResponse({"message": "EMAIL_ERROR"}, status=400)
생각해보니 굳이 필요 없을거 같습니다. 이메일 중복은 uniqu 옵션으로하고 except 쪽으로 오류 메세지 출력하면 될거 같습니다

2021-11-19 11:24 UTC, jincastle commented on students/jinsungpark/users/views.py
> +class UsersView(View):
SignUp으로 변경 완료하였습니다

2021-11-19 11:28 UTC, jincastle commented on students/jinsungpark/users/views.py
> +            passwd = data["passwd"],
넵 passwd = password  수정 완료했습니다

2021-11-19 11:29 UTC, jincastle commented on students/jinsungpark/users/views.py
> +        except:
except Exception 추가하여 Key_Error로 빠지게 했습니다.

2021-11-19 12:23 UTC, jincastle commented on students/jinsungpark/users/views.py
> +        except:
except를 이용해서 KeyError, IntegrityError 분리하였습니다

2021-11-21 15:28 UTC, kyeongraekim requested changes
안녕하세요 진성님~ 아래 내용 확인후 수정해주세요!~

2021-11-21 15:28 UTC, kyeongraekim commented on students/jinsungpark/users/urls.py
> +from .views import SignUpView, LogInView
위코드 컨벤션에 맞게 깔끔한 재정렬 부탁드립니다~

2021-11-21 15:28 UTC, kyeongraekim commented on students/jinsungpark/users/urls.py
> +    path("/login",LogInView.as_view())
회원가입 뷰에 불필요한 url 이 보이네요! 그리고 회원가입 뷰에 맞는 디렉팅을 위해서 빈스트링열보다 구체적으로 url을 설정해주세요!!~

2021-11-21 15:28 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +from .models import User
컨벤션에 맞게 임포트 문들을 재정렬해주세요!~
그리고 위 아래를 판단해주시고 사용하지 않는 불필요한 임포트문은 삭제해주세요!~

2021-11-21 15:28 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +            passwd_condition = '^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$'
실제로 정규표현식을 썼다는 내용을 보다 정확하게 파악하기 위해서 regex 라는 변수명이 들어가면 더 좋을 것 같아 보입니다~

2021-11-21 15:28 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +                return JsonResponse({"result" : "INVALID_USER"}, status=401)
논리상 if-elif 구조로 꼭 작성이 되어야 하는 내용일까요? 세가지 내용이 꼭 함께 연산되어야 하는 내용인지 다시 한 번 고민해주세요!
그리고 세번째 리스폰스도 message 로 통일 시켜도 무방해보입니다!~

2021-11-22 01:01 UTC, jincastle commented on students/jinsungpark/users/views.py
> +                return JsonResponse({"result" : "INVALID_USER"}, status=401)
message로 변경했습니다.

2021-11-22 01:02 UTC, jincastle commented on students/jinsungpark/users/views.py
> +            passwd_condition = '^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$'
email_regex, passwd_regex로 변경했습니다.

2021-11-22 01:02 UTC, jincastle commented on students/jinsungpark/users/views.py
> +from .models import User
필요없는 컨벤션 삭제 처리했습니다.

2021-11-22 01:02 UTC, jincastle commented on students/jinsungpark/users/urls.py
> +    path("/login",LogInView.as_view())
불피요한 url과 회원가입 /signup으로 수정하였습니다.

2021-11-22 01:04 UTC, jincastle commented on students/jinsungpark/users/urls.py
> +from .views import SignUpView, LogInView
컨벤션 정리 하였습니다.

2021-11-22 02:12 UTC, kyeongraekim requested changes
아래 내용 참고해서 수정해주세요!~

2021-11-22 02:12 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
>  # Create your views here.
불필요한 영어 주석은 삭제해주세요!~

2021-11-22 02:12 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +            passwd_regex = '^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$'
컨벤션에 맞게 정렬해주세요!~ git add commit  전에 git diff 명령어를 쳐봄으로써 실제 어떠한 포맷으로 깃허브에 반영되어서 올라가는지 사전 확인 부탁드립니다~

2021-11-22 02:12 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +                return JsonResponse({"message": "PW_ERROR"}, status=400)
변수명과 마찬가지로 리터메세지도 늘 영어 원어 전체 단어를 사용하는 것을 지향해주세요!~

2021-11-22 02:12 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +        except KeyError:
Except 문에 앞서 라인 한칸 공백 추가해주세요~

2021-11-22 02:12 UTC, kyeongraekim commented on students/jinsungpark/users/views.py
> +        except IntegrityError:
IntegrityError 는 db의 무결성이 영향을 받게 되는 모든 경우의 수에서 나는 에러이기 때문에 Email을 잘못 써준 것에 대한 것만 메세지를 리턴해서 보내주면 다소 모순점이 있을 수 있습니다. ValidationError 등 다른 내용으로 바꾸어 주세요!~

2021-11-22 02:28 UTC, jincastle commented on students/jinsungpark/users/views.py
> +            passwd_regex = '^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$'
확인후 다시 올렸습니다

2021-11-22 02:29 UTC, jincastle commented on students/jinsungpark/users/views.py
> +                return JsonResponse({"message": "PW_ERROR"}, status=400)
넵 PW -> PASSWORD 수정 완료했습니다. 다음부터 영어 원어 사용하겠습니다.

2021-11-22 02:29 UTC, jincastle commented on students/jinsungpark/users/views.py
> +        except KeyError:
수정완료했습니다.

2021-11-22 02:29 UTC, jincastle commented on students/jinsungpark/users/views.py
>  # Create your views here.
불필요한 영어 삭제하였습니다.

2021-11-22 03:16 UTC, jincastle commented on students/jinsungpark/users/views.py
> +        except IntegrityError:
ValidationError로 변경 완료했습니다

2021-11-22 06:41 UTC, bigfanoftim requested changes

2021-11-22 06:41 UTC, bigfanoftim commented on students/jinsungpark/users/views.py
> +from .models                import User
불필요한 import문은 지워주시고, import문 순서를 잘 지켜서 만들어주세요.
위와 같은 순서대로 import 하는 모듈을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.
(python convention 문서 참고해주세요.)

```
# 파이썬 built-in 모듈
import re, json

# 외부 모듈
from django.http      import JsonResponse
from django.views     import View

# 내가 만든 사용자 모듈
from users.models     import User
```

2021-11-22 06:41 UTC, bigfanoftim commented on students/jinsungpark/users/views.py
> +                return JsonResponse({"message": "EMAIL_ERROR"}, status=400)
파이썬에서는 `if 조건문` 평가시, 반환 되는 값 자체가 `boolean` 일 경우나, `Truthy`, `Falsy` 한 값일 경우,  `== False` `== None` `== 0`등으로 평가하지 않고, 그 값을 그대로 사용합니다. 그 자체로도 `True or False`를 판단할 수 있기 때문입니다. `False`한 지 평가하실 때는 `not` 을 활용해보세요 :)
```suggestion
```

2021-11-22 06:41 UTC, bigfanoftim commented on students/jinsungpark/users/views.py
> +            if re.match(passwd_regex, data["password"]) is None:
위와 같습니다.

2021-11-22 06:41 UTC, bigfanoftim commented on students/jinsungpark/users/views.py
> +                return JsonResponse({"message" : "INVALID_USER"}, status=401)
작성하신 코드와 에러 메세지가 어울리지 않는 것 같습니다. 확인해주세요.
```suggestion
```

2021-11-22 07:22 UTC, jincastle commented on students/jinsungpark/users/views.py
> +                return JsonResponse({"message" : "INVALID_USER"}, status=401)
에러발생에 맞게 메세지 변경하였습니다.

2021-11-22 07:22 UTC, jincastle commented on students/jinsungpark/users/views.py
> +                return JsonResponse({"message": "EMAIL_ERROR"}, status=400)
not으로 변경하였습니다.

2021-11-22 07:30 UTC, merged